# https://numtide.github.io/devshell
[[env]]
name = "DECKDIR"
value = "/home/deck"

[[env]]
name = "DECKKEY"
eval = "$HOME/.ssh/id_rsa"

[[env]]
name = "DECKPASS"
value = "22"

[[env]]
name = "DECKPORT"
value = "22"

[[env]]
name = "DECKIP"
value = "192.168.1.229"


[[commands]]
package = "devshell.cli"
help = "Per project developer environments"


[[commands]]
package = "nodejs-18_x"
name = "node"

[[commands]]
package = "nodePackages.prettier"


[[commands]]
package = "just"
help = "Our command-runner. Similar to Makefile. Run `just --list` to see the available commands"
